### ISSUE TITLE
DeviantArt No images Found error

### ISSUE THREAD

**Issue by andrerdxd** [RipMeApp/ripme#108] opened 2017-10-17 20:33 UTC
hi i keep getting this error with devianart and in the log file appears this:

2017-10-06 13:38:49,705 DEBUG ripper.DownloadThreadPool .initialize() Initializing Main thread pool with 5 threads
2017-10-06 13:38:49,706 INFO  ripper.AbstractRipper .rip() Retrieving https://polinaegorussia.deviantart.com/gallery/?catpath=/
2017-10-06 13:38:52,497 WARN  ripper.AbstractRipper .getFirstPage() Failed to login: 
java.io.IOException: Login form was incorrectly submitted
	at com.rarchives.ripme.ripper.rippers.DeviantartRipper.loginToDeviantart(DeviantartRipper.java:438)
	at com.rarchives.ripme.ripper.rippers.DeviantartRipper.getFirstPage(DeviantartRipper.java:115)
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:68)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:353)
	at java.lang.Thread.run(Unknown Source)
2017-10-06 13:38:53,601 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.io.IOException: No images found at https://polinaegorussia.deviantart.com/gallery/?catpath=/
	at com.rarchives.ripme.ripper.AbstractHTMLRipper.rip(AbstractHTMLRipper.java:80)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:353)
	at java.lang.Thread.run(Unknown Source)
2017-10-06 13:38:53,602 DEBUG ripper.AbstractRipper .waitForThreads() Waiting for threads to finish
2017-10-06 13:38:53,602 INFO  ripper.AbstractRipper .checkIfComplete()    Rip completed!
2017-10-06 13:38:53,602 DEBUG ripper.AbstractRipper .checkIfComplete() Changing log file back to 'ripme.log'

**Comment by rautamiekka** [comment] 2017-10-17 20:48
RipMe version ? Operating system version ? Java maker and version ?

**Comment by andrerdxd** [comment] 2017-10-17 20:51
RipMe version: 1.5.14
Operating system version: windows 10
Java version: 8

**Comment by rautamiekka** [comment] 2017-10-17 20:58
^
>Java version: 8

Which Update ? 144 ?

**Comment by rautamiekka** [comment] 2017-10-17 21:00
The problem is explained in https://github.com/RipMeApp/ripme/issues/92

**Comment by andrerdxd** [comment] 2017-10-17 21:04
yes, 144, gonna see that issue you posted

**Comment by andrerdxd** [comment] 2017-10-17 21:05
so there is no fix yet?

**Comment by rautamiekka** [comment] 2017-10-17 21:08
^ No. Either the RipMe acc has wrong pw, or RipMe ain't succeeding in logging in.

**Comment by andrerdxd** [comment] 2017-10-17 21:11
ok thanks for all the help!

**Comment by metaprime** [comment] 2017-11-29 12:01
Duplicate of #92

**Closed by metaprime** 2017-11-29 12:01 UTC
Labels: duplicate
