### ISSUE TITLE
Deviantart gallery issues

### ISSUE THREAD

**Issue by cake22** [RipMeApp/ripme#773] opened 2018-07-04 14:49 UTC
* Ripme version: v1.7.57
* Java version:  Version 8 Update 171 (build 1.8.0_171-b11)
* Operating system:  macOS High Sierra

* Exact URL you were trying to rip when the problem occurred: (NSFW)https://www.deviantart.com/victorzulu/gallery/?catpath=/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Download gallery images

## Actual Behavior

Downloads only 2 images each  time and then stops. I have tried playing around with the url as well (i.e. downloading from Featured vs All within deviantart's gallery page, but the result is the same)

**Comment by inkplay** [comment] 2018-07-04 19:45
I got another issue as well.

Ripme version: v1.7.57
Java version: Version 8 Update 171 (build 1.8.0_171-b11)
Operating system: Windows 10
Exact URL you were trying to rip when the problem occurred: 
https://www.deviantart.com/popular-all-time/?section=&global=1&q=lineart
Please include any additional information about how to reproduce the problem:
Expected Behavior
Download gallery images

Actual Behavior
Doesn't download anything but it would tell you download is complete with no error thrown.

**Comment by cyian-1756** [comment] 2018-07-05 07:54
@inkplay 

> I got another issue as well.

Please make a new issue for that

**Comment by cyian-1756** [comment] 2018-07-05 07:57
Looks like this is happening because the user has 3 images in https://www.deviantart.com/victorzulu/gallery/, one of which is a NSFW link that the ripper doesn't support yet. The fix for this seems to be setting galleryID to 0 or null when ripping from ?catpath=/

I'll get on fixing this

**Closed** 2018-07-07 21:37 UTC
Labels: confirmed
