### ISSUE TITLE
Instagram issue in 1.7.25

### ISSUE THREAD

**Issue by Benwebdev** [RipMeApp/ripme#476] opened 2018-03-15 12:11 UTC
* Ripme version: 1.7.25
* Java version: 
* Operating system: Windows
* Exact URL you were trying to rip when the problem occurred: 
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

To download instagram images. 

## Actual Behavior

When ripping instagram with the new update it's telling me the photo has already have been ripped when in fact they haven't and when I turn off save URL's it then just circles through the pages without downloading anything. 

So it downloads 12 images and stops and just then circles through the pages.

**Comment by darko1x** [comment] 2018-03-15 12:26
i'm having the same issue, i only get the first 12 pics/videos

**Comment by darko1x** [comment] 2018-03-15 12:30
the same thing happened with jdownloader, could this be an api issue ?

**Comment by cyian-1756** [comment] 2018-03-15 17:21
This is a dupe of #474 

@darko1x 

> could this be an api issue

Yup. Ripme changed their JSON structure as well as what endpoint you call to get the next page

**Closed by cyian-1756** 2018-03-15 17:21 UTC
Labels: duplicate

**Comment by cyian-1756** [comment] 2018-03-15 17:44
This should be fixed in 1.7.26
