### ISSUE TITLE
No Sound in Video

### ISSUE THREAD

**Issue by samkarpenter** [RipMeApp/ripme#1241] opened 2019-03-12 08:40 UTC
Hello, when the script rips videos, they have no sound! Is there a way to work around it? I know that Reddit doens't serve sound when you do a direct DL, but Ripsave.com somehow accomplishes it! Your help will be greatly appreciated!

**Comment by cyian-1756** [comment] 2019-05-06 23:38
This is a dupe of #852

**Closed by cyian-1756** 2019-05-06 23:38 UTC
