### ISSUE TITLE
Deviantart Downloader Still Not WorkingCan't Download Gallery Folders

### ISSUE THREAD

**Issue by IcedKoohii** [RipMeApp/ripme#778] opened 2018-07-05 15:48 UTC
Ripme version: v1.7.57

    Java version: Version 8 Update 171 (build 1.8.0_171-b11)

    Operating system: Windows 10

* Exact URL you were trying to rip when the problem occurred: https://www.deviantart.com/kibbitzer/gallery/51429391/Reference-Sheets
* Please include any additional information about how to reproduce the problem:

## Expected Behavior
Copy and paste link into ripper
(deviantart album detected)
Rip and gallery downloads

## Actual Behavior
Copy and pasted Link into Ripper
(deviantart album detected)
Click rip
(Error: Failed to load [Link] after 1 attempts)
Nothing Downloads
[log.txt](https://github.com/RipMeApp/ripme/files/2167261/log.txt)

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by rephormat** [comment] 2018-07-05 16:32
Duplicate of #774 
Recommend closing.

**Comment by cyian-1756** [comment] 2018-07-06 05:12
Closing this as a duplicate of #774

**Closed by cyian-1756** 2018-07-06 05:12 UTC
Labels: duplicate
