### ISSUE TITLE
xhamster seems to not be working. ripme seems to go out to the site but does not download [NSFW]

### ISSUE THREAD

**Issue by wraith64** [RipMeApp/ripme#263] opened 2017-11-21 13:42 UTC
version 1.6.13
Java 8.01510.12
xhamster seems to not be working. ripme seems to go out to the site but does not download or create a folder

https://xhamster.com/photos/gallery/beautiful-hailey-leigh-3855137

all urls are affected

log:
Downloading http://up.xhamster.com/000/064/724/260_1000.jpg
Downloading http://up.xhamster.com/000/064/724/260_1000.jpg
Downloading http://up.xhamster.com/000/064/724/260_1000.jpg
Downloading http://up.xhamster.com/000/064/725/055_1000.jpg
Downloading http://up.xhamster.com/000/064/724/260_1000.jpg
Downloading http://up.xhamster.com/000/064/725/055_1000.jpg
Downloading http://up.xhamster.com/000/064/724/260_1000.jpg
Downloading http://up.xhamster.com/000/064/725/055_1000.jpg
http://up.xhamster.com/000/064/724/260_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/260_1000.jpg
Downloading http://up.xhamster.com/000/064/725/054_1000.jpg
Downloading http://up.xhamster.com/000/064/725/055_1000.jpg
Downloading http://up.xhamster.com/000/064/725/054_1000.jpg
Downloading http://up.xhamster.com/000/064/725/055_1000.jpg
Downloading http://up.xhamster.com/000/064/725/054_1000.jpg
http://up.xhamster.com/000/064/725/055_1000.jpg : Failed to download http://up.xhamster.com/000/064/725/055_1000.jpg
Downloading http://up.xhamster.com/000/064/725/054_1000.jpg
Downloading http://up.xhamster.com/000/064/725/053_1000.jpg
Downloading http://up.xhamster.com/000/064/725/054_1000.jpg
Downloading http://up.xhamster.com/000/064/725/053_1000.jpg
http://up.xhamster.com/000/064/725/054_1000.jpg : Failed to download http://up.xhamster.com/000/064/725/054_1000.jpg
Downloading http://up.xhamster.com/000/064/725/053_1000.jpg
Downloading http://up.xhamster.com/000/064/725/052_1000.jpg
Downloading http://up.xhamster.com/000/064/725/053_1000.jpg
Downloading http://up.xhamster.com/000/064/725/052_1000.jpg
Downloading http://up.xhamster.com/000/064/725/053_1000.jpg
Downloading http://up.xhamster.com/000/064/725/052_1000.jpg
http://up.xhamster.com/000/064/725/053_1000.jpg : Failed to download http://up.xhamster.com/000/064/725/053_1000.jpg
Downloading http://up.xhamster.com/000/064/725/051_1000.jpg
Downloading http://up.xhamster.com/000/064/725/052_1000.jpg
Downloading http://up.xhamster.com/000/064/725/051_1000.jpg
Downloading http://up.xhamster.com/000/064/725/052_1000.jpg
http://up.xhamster.com/000/064/725/052_1000.jpg : Failed to download http://up.xhamster.com/000/064/725/052_1000.jpg
Downloading http://up.xhamster.com/000/064/725/051_1000.jpg
Downloading http://up.xhamster.com/000/064/725/051_1000.jpg
Downloading http://up.xhamster.com/000/064/725/050_1000.jpg
Downloading http://up.xhamster.com/000/064/725/051_1000.jpg
Downloading http://up.xhamster.com/000/064/725/050_1000.jpg
http://up.xhamster.com/000/064/725/051_1000.jpg : Failed to download http://up.xhamster.com/000/064/725/051_1000.jpg
Downloading http://up.xhamster.com/000/064/725/050_1000.jpg
Downloading http://up.xhamster.com/000/064/725/050_1000.jpg
Downloading http://up.xhamster.com/000/064/725/049_1000.jpg
Downloading http://up.xhamster.com/000/064/725/050_1000.jpg
Downloading http://up.xhamster.com/000/064/725/049_1000.jpg
http://up.xhamster.com/000/064/725/050_1000.jpg : Failed to download http://up.xhamster.com/000/064/725/050_1000.jpg
Downloading http://up.xhamster.com/000/064/725/049_1000.jpg
Downloading http://up.xhamster.com/000/064/725/048_1000.jpg
Downloading http://up.xhamster.com/000/064/725/049_1000.jpg
Downloading http://up.xhamster.com/000/064/725/048_1000.jpg
Downloading http://up.xhamster.com/000/064/725/049_1000.jpg
Downloading http://up.xhamster.com/000/064/725/048_1000.jpg
http://up.xhamster.com/000/064/725/049_1000.jpg : Failed to download http://up.xhamster.com/000/064/725/049_1000.jpg
Downloading http://up.xhamster.com/000/064/725/048_1000.jpg
Downloading http://up.xhamster.com/000/064/725/048_1000.jpg
Downloading http://up.xhamster.com/000/064/725/047_1000.jpg
http://up.xhamster.com/000/064/725/048_1000.jpg : Failed to download http://up.xhamster.com/000/064/725/048_1000.jpg
Downloading http://up.xhamster.com/000/064/725/047_1000.jpg
Downloading http://up.xhamster.com/000/064/725/047_1000.jpg
Downloading http://up.xhamster.com/000/064/725/047_1000.jpg
Downloading http://up.xhamster.com/000/064/725/047_1000.jpg
http://up.xhamster.com/000/064/725/047_1000.jpg : Failed to download http://up.xhamster.com/000/064/725/047_1000.jpg
Downloading http://up.xhamster.com/000/064/725/046_1000.jpg
Downloading http://up.xhamster.com/000/064/725/046_1000.jpg
Downloading http://up.xhamster.com/000/064/725/046_1000.jpg
Downloading http://up.xhamster.com/000/064/725/046_1000.jpg
Downloading http://up.xhamster.com/000/064/725/046_1000.jpg
http://up.xhamster.com/000/064/725/046_1000.jpg : Failed to download http://up.xhamster.com/000/064/725/046_1000.jpg
Downloading http://up.xhamster.com/000/064/725/045_1000.jpg
Downloading http://up.xhamster.com/000/064/725/045_1000.jpg
Downloading http://up.xhamster.com/000/064/725/045_1000.jpg
Downloading http://up.xhamster.com/000/064/725/045_1000.jpg
Downloading http://up.xhamster.com/000/064/725/045_1000.jpg
http://up.xhamster.com/000/064/725/045_1000.jpg : Failed to download http://up.xhamster.com/000/064/725/045_1000.jpg
Downloading http://up.xhamster.com/000/064/724/501_1000.jpg
Downloading http://up.xhamster.com/000/064/724/501_1000.jpg
Downloading http://up.xhamster.com/000/064/724/501_1000.jpg
Downloading http://up.xhamster.com/000/064/724/501_1000.jpg
Downloading http://up.xhamster.com/000/064/724/501_1000.jpg
http://up.xhamster.com/000/064/724/501_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/501_1000.jpg
Downloading http://up.xhamster.com/000/064/724/500_1000.jpg
Downloading http://up.xhamster.com/000/064/724/500_1000.jpg
Downloading http://up.xhamster.com/000/064/724/500_1000.jpg
Downloading http://up.xhamster.com/000/064/724/500_1000.jpg
Downloading http://up.xhamster.com/000/064/724/500_1000.jpg
http://up.xhamster.com/000/064/724/500_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/500_1000.jpg
Downloading http://up.xhamster.com/000/064/724/499_1000.jpg
Downloading http://up.xhamster.com/000/064/724/499_1000.jpg
Downloading http://up.xhamster.com/000/064/724/499_1000.jpg
Downloading http://up.xhamster.com/000/064/724/499_1000.jpg
Downloading http://up.xhamster.com/000/064/724/499_1000.jpg
http://up.xhamster.com/000/064/724/499_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/499_1000.jpg
Downloading http://up.xhamster.com/000/064/724/498_1000.jpg
Downloading http://up.xhamster.com/000/064/724/498_1000.jpg
Downloading http://up.xhamster.com/000/064/724/498_1000.jpg
Downloading http://up.xhamster.com/000/064/724/498_1000.jpg
Downloading http://up.xhamster.com/000/064/724/498_1000.jpg
http://up.xhamster.com/000/064/724/498_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/498_1000.jpg
Downloading http://up.xhamster.com/000/064/724/497_1000.jpg
Downloading http://up.xhamster.com/000/064/724/497_1000.jpg
Downloading http://up.xhamster.com/000/064/724/497_1000.jpg
Downloading http://up.xhamster.com/000/064/724/497_1000.jpg
Downloading http://up.xhamster.com/000/064/724/497_1000.jpg
http://up.xhamster.com/000/064/724/497_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/497_1000.jpg
Downloading http://up.xhamster.com/000/064/724/496_1000.jpg
Downloading http://up.xhamster.com/000/064/724/496_1000.jpg
Downloading http://up.xhamster.com/000/064/724/496_1000.jpg
Downloading http://up.xhamster.com/000/064/724/496_1000.jpg
Downloading http://up.xhamster.com/000/064/724/496_1000.jpg
http://up.xhamster.com/000/064/724/496_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/496_1000.jpg
Downloading http://up.xhamster.com/000/064/724/495_1000.jpg
Downloading http://up.xhamster.com/000/064/724/495_1000.jpg
Downloading http://up.xhamster.com/000/064/724/495_1000.jpg
Downloading http://up.xhamster.com/000/064/724/495_1000.jpg
Downloading http://up.xhamster.com/000/064/724/494_1000.jpg
Downloading http://up.xhamster.com/000/064/724/495_1000.jpg
Downloading http://up.xhamster.com/000/064/724/494_1000.jpg
http://up.xhamster.com/000/064/724/495_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/495_1000.jpg
Downloading http://up.xhamster.com/000/064/724/494_1000.jpg
Downloading http://up.xhamster.com/000/064/724/494_1000.jpg
Downloading http://up.xhamster.com/000/064/724/494_1000.jpg
http://up.xhamster.com/000/064/724/494_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/494_1000.jpg
Downloading http://up.xhamster.com/000/064/724/493_1000.jpg
Downloading http://up.xhamster.com/000/064/724/493_1000.jpg
Downloading http://up.xhamster.com/000/064/724/493_1000.jpg
Downloading http://up.xhamster.com/000/064/724/493_1000.jpg
Downloading http://up.xhamster.com/000/064/724/269_1000.jpg
Downloading http://up.xhamster.com/000/064/724/493_1000.jpg
Downloading http://up.xhamster.com/000/064/724/269_1000.jpg
Downloading http://up.xhamster.com/000/064/724/269_1000.jpg
http://up.xhamster.com/000/064/724/493_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/493_1000.jpg
Downloading http://up.xhamster.com/000/064/724/269_1000.jpg
Downloading http://up.xhamster.com/000/064/724/268_1000.jpg
Downloading http://up.xhamster.com/000/064/724/269_1000.jpg
Downloading http://up.xhamster.com/000/064/724/268_1000.jpg
http://up.xhamster.com/000/064/724/269_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/269_1000.jpg
Downloading http://up.xhamster.com/000/064/724/268_1000.jpg
Downloading http://up.xhamster.com/000/064/724/267_1000.jpg
Downloading http://up.xhamster.com/000/064/724/268_1000.jpg
Downloading http://up.xhamster.com/000/064/724/267_1000.jpg
Downloading http://up.xhamster.com/000/064/724/268_1000.jpg
Downloading http://up.xhamster.com/000/064/724/267_1000.jpg
http://up.xhamster.com/000/064/724/268_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/268_1000.jpg
Downloading http://up.xhamster.com/000/064/724/267_1000.jpg
Downloading http://up.xhamster.com/000/064/724/266_1000.jpg
Downloading http://up.xhamster.com/000/064/724/267_1000.jpg
Downloading http://up.xhamster.com/000/064/724/266_1000.jpg
http://up.xhamster.com/000/064/724/267_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/267_1000.jpg
Downloading http://up.xhamster.com/000/064/724/266_1000.jpg
Downloading http://up.xhamster.com/000/064/724/266_1000.jpg
Downloading http://up.xhamster.com/000/064/724/265_1000.jpg
Downloading http://up.xhamster.com/000/064/724/266_1000.jpg
Downloading http://up.xhamster.com/000/064/724/265_1000.jpg
http://up.xhamster.com/000/064/724/266_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/266_1000.jpg
Downloading http://up.xhamster.com/000/064/724/264_1000.jpg
Downloading http://up.xhamster.com/000/064/724/265_1000.jpg
Downloading http://up.xhamster.com/000/064/724/264_1000.jpg
Downloading http://up.xhamster.com/000/064/724/265_1000.jpg
Downloading http://up.xhamster.com/000/064/724/264_1000.jpg
Downloading http://up.xhamster.com/000/064/724/265_1000.jpg
Downloading http://up.xhamster.com/000/064/724/263_1000.jpg
Downloading http://up.xhamster.com/000/064/724/264_1000.jpg
http://up.xhamster.com/000/064/724/265_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/265_1000.jpg
Downloading http://up.xhamster.com/000/064/724/263_1000.jpg
Downloading http://up.xhamster.com/000/064/724/264_1000.jpg
Downloading http://up.xhamster.com/000/064/724/263_1000.jpg
Downloading http://up.xhamster.com/000/064/724/262_1000.jpg
Downloading http://up.xhamster.com/000/064/724/263_1000.jpg
http://up.xhamster.com/000/064/724/264_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/264_1000.jpg
Downloading http://up.xhamster.com/000/064/724/262_1000.jpg
Downloading http://up.xhamster.com/000/064/724/263_1000.jpg
Downloading http://up.xhamster.com/000/064/724/262_1000.jpg
http://up.xhamster.com/000/064/724/263_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/263_1000.jpg
Downloading http://up.xhamster.com/000/064/724/262_1000.jpg
Downloading http://up.xhamster.com/000/064/724/261_1000.jpg
Downloading http://up.xhamster.com/000/064/724/262_1000.jpg
Downloading http://up.xhamster.com/000/064/724/261_1000.jpg
http://up.xhamster.com/000/064/724/262_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/262_1000.jpg
Downloading http://up.xhamster.com/000/064/724/261_1000.jpg
Downloading http://up.xhamster.com/000/064/724/261_1000.jpg
Downloading http://up.xhamster.com/000/064/724/261_1000.jpg
http://up.xhamster.com/000/064/724/261_1000.jpg : Failed to download http://up.xhamster.com/000/064/724/261_1000.jpg
Rip complete, saved to C:\Users\Ron\Downloads\Completed\rips\New Folder\xhamster_3855137

**Comment by cyian-1756** [comment] 2017-11-21 18:49
I can rip https://xhamster.com/photos/gallery/beautiful-hailey-leigh-3855137 without issue. Could you post your log / go to https://xhamster.com/photos/gallery/beautiful-hailey-leigh-3855137 in a browser, right click and select "view source", copy and paste everything there into a text file and share that text file here? I ask because I suspect this a issue with Xhamsers regional CDNs

**Comment by metaprime** [comment] 2017-11-21 20:07
Also confirmed the rip works fine from here. Definitely interested in more details.

**Comment by wraith64** [comment] 2017-11-23 03:12
Hi metaprime and cyian-1756...

I got flagged briefly... I am back now. I posted the text file. Also as an experiment I tried xhamster through a VPN. Still did not work. I do have success with other supported sites.

Let me know if there is anything else I can help with.

**Comment by cyian-1756** [comment] 2017-11-23 03:36
@wraith64 Can you download http://up.xhamster.com/000/064/725/051_1000.jpg if use a web browser?

**Comment by wraith64** [comment] 2017-11-24 12:13
@cyian-1756 

RE: @wraith64 Can you download http://up.xhamster.com/000/064/725/051_1000.jpg if use a web browser?

Yes... no problems downloading that link through my browser which is (as of today) Firefox Quantum 57.0 and up to date.

**Comment by cyian-1756** [comment] 2017-11-24 17:34
> Yes... no problems downloading that link through my browser which is (as of today) Firefox Quantum 57.0 and up to date.

Then I have no idea what's causing this issue. I say try ripping xhamster again and see if it works this time

**Comment by wraith64** [comment] 2017-11-28 14:17
tried again with version 1.7.3 still no joy.

**Comment by cyian-1756** [comment] 2017-11-28 18:15
Can you download http://up.xhamster.com/000/064/725/051_1000.jpg if use a web browser?

**Comment by metaprime** [comment] 2017-11-29 10:45
@cyian-1756 is there any difference between the html he posted and what you see in a web browser?

**Comment by wraith64** [comment] 2017-11-29 15:36
Happy to post logs, urls, or anything you think may help. It is very odd, it worked flawlessly using the same laptop, browser, etc. Then it just stopped working with no changes on my end. I assumed that there was a change at xhamster since I had changed nothing. I then (sequentially) upgraded to the most current ripme, then Java, then my browser. Also tried on both old and new versions of xhamsters webviews. Odd.

**Comment by cyian-1756** [comment] 2017-11-29 22:02
> is there any difference between the html he posted and what you see in a web browser?

@metaprime Nope.

**Comment by metaprime** [comment] 2017-11-30 06:39
@wraith64 any improvement in the latest ripme now that we've moved to the mobile site?

**Comment by wraith64** [comment] 2017-12-01 04:38
Unfortunately, no change.

**Comment by metaprime** [comment] 2017-12-01 19:11
Dang...

**Comment by wraith64** [comment] 2017-12-01 20:00
Is there a cache file to delete or an uninstall I should try before using a new version of ripme? *he said, grasping at straws*

**Comment by cyian-1756** [comment] 2017-12-01 21:15
> Is there a cache file to delete or an uninstall I should try before using a new version of ripme?

No.

Can you download http://up.xhamster.com/000/064/725/051_1000.jpg if use a web browser?

Can you try downloading http://up.xhamster.com/000/064/725/051_1000.jpg using wget and poweshell?

**Comment by wraith64** [comment] 2017-12-01 22:17
Just to clarify when you say "can I download in the web browser" do we mean simply open the page in the browser, see the image, be able to right click and download the file in a typical way without any errors or incidents?

If so, I will try it again for completeness when I get back to my computer. I will also try the other two requested actions then as well. Thank you for time and effort!

**Comment by cyian-1756** [comment] 2017-12-01 22:31
> Just to clarify when you say "can I download in the web browser" do we mean simply open the page in the browser, see the image, be able to right click and download the file in a typical way without any errors or incidents?

Yes.

> If so, I will try it again for completeness when I get back to my computer. I will also try the other two requested actions then as well.

Great! 

> Thank you for time and effort!

You're welcome

**Comment by evaporatedwhiz** [comment] 2017-12-04 13:19
Apologies if this is already known, but it affects Xhamster videos as well. Here's what I'm showing

Could not find Embed code at https://xhamster.com/videos/blow-job-for-kentucky-cowboy-7306750
Rip complete, saved to D:\rips\videos
Could not find Embed code at https://xhamster.com/videos/blow-job-for-kentucky-cowboy-and-doggy-style-cum-shot-7332318
Rip complete, saved to D:\rips\videos

**Comment by rephormat** [comment] 2018-01-13 22:55
Currently working on a fix for this.

**Comment by cyian-1756** [comment] 2018-01-13 23:13
@rephormat I'm pretty sure this was already fixed when I changed the ripper to use the mobile site instead of the desktop site (As the desktop site some times redirected you to the beta version)

@wraith64 Is xhamster working now?

**Comment by rephormat** [comment] 2018-01-14 00:18
@cyian-1756 I'm currently running v1.7.12 and have verified the error above by @evaporatedwhiz  Are you running on a different version?

**Comment by cyian-1756** [comment] 2018-01-14 02:54
@rephormat 

I completely missed evaporatedwhiz's comment and thought you were talking about image albums not downloading.

I have also confirmed @evaporatedwhiz issue

**Comment by cyian-1756** [comment] 2018-01-14 03:00
@rephormat

@evaporatedwhiz 

I've made a new issue (#388) for tracking the xhamster video bug

**Comment by rephormat** [comment] 2018-01-14 17:17
@cyian-1756 

I suggest closing this issue if we don't hear back from @wraith64 soon to cleanup dead or irrelevant issues.  Thoughts?

**Comment by cyian-1756** [comment] 2018-01-15 05:15
> I suggest closing this issue if we don't hear back from @wraith64 soon to cleanup dead or irrelevant issues

I agree. if he hasn't commented in the next day I'll close the issue

**Comment by evaporatedwhiz** [comment] 2018-01-16 17:38
Can't vouch for @wraith64 issue, but mine has resolved. thanks guys!

**Comment by rephormat** [comment] 2018-01-16 17:41
@evaporatedwhiz Glad to hear it.

**Comment by cyian-1756** [comment] 2018-01-16 19:12
As @wraith64 hasn't responded I'm assume this issue was fixed

**Closed by cyian-1756** 2018-01-16 19:12 UTC
Labels: bug, client issue
