### ISSUE TITLE
Fuskator ripping problem. Url needs to be inputted more than once to work.

### ISSUE THREAD

**Issue by ringofyre** [RipMeApp/ripme#549] opened 2018-04-27 20:49 UTC
* Ripme version:1.7.39
* Java version: openjdk version "1.8.0_162"
* Operating system: Linux X202EP 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux 
* Exact URL you were trying to rip when the problem occurred:https://fuskator.com/full/-nv-FJE62Zd/Shaved-Malinda-A-with-Open-Pussy.html
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Should rip and doesn't.

## Actual Behavior

Rips often on second or third attempt.

**Comment by cyian-1756** [comment] 2018-04-29 03:31
I can't reproduce this with ripme 1.7.39 with openjdk version "1.8.0_162". Can you post your logs?

**Comment by cyian-1756** [comment] 2018-06-03 23:55
@ringofyre I'm closing this as I can't reproduce it, if you post your logs from when you run into this issue I'll reopen it

**Closed by cyian-1756** 2018-06-03 23:55 UTC
Labels: can't repro
