### ISSUE TITLE
DeviantArt Favorites Folder

### ISSUE THREAD

**Issue by xex24** [RipMeApp/ripme#836] opened 2018-07-26 12:44 UTC
* Ripme version:1.7.60
* Java version: 8_181
* Operating system: Parrot 3.5

* Exact URL you were trying to rip when the problem occurred:
https://www.deviantart.com/simplysilent/favourites/51119411/Awesome
* Please include any additional information about how to reproduce the problem:
It can't download any deviantart user's favorites folder...
## Expected Behavior

Expected to download the favorites folder from a user on DeviantArt.

## Actual Behavior

Im getting this error .." Expected URL format: http://www,deviantart.com/username[/gallery/#####], got: https://www.deviantart.com/simplysilent/favourites/51119411/Awesome/gallery "...
The programm adds "/gallery" on the url and not only that, it can't download favorites!

**Comment by cyian-1756** [comment] 2018-07-26 14:16
I'm closing this as it's a dupe of #826

**Closed by cyian-1756** 2018-07-26 14:16 UTC
