### ISSUE TITLE
mvn test failing

### ISSUE THREAD

**Issue by ghost** [RipMeApp/ripme#21] opened 2017-07-15 17:01 UTC
* Ripme version: latest code
* Java version: 1.8.0_66
* Operating system: os x (10.10.5)

'mvn test' is failing. I have attached the output here.

[test_log.txt](https://github.com/RipMeApp/ripme/files/1150481/test_log.txt)

**Comment by raviteja1992y** [comment] 2017-07-15 17:06
In the home page, it was written to use 'mvn test'. But when I run 'mvn test', most of the tests are failing. I think we should run only few tests in mvn test, if possible. That way it would be easy for beginners.

**Comment by rautamiekka** [comment] 2017-07-16 23:12
Which commit as shown at https://github.com/RipMeApp/ripme ? ATM when I checked it's https://github.com/RipMeApp/ripme/commit/4e2d5f3c6e551b95a7106e8eeb1c52eedbac610c while the whole string reads `Latest commit 4e2d5f3 4 days ago`.

Besides, you're on an **ancient** Java.

**Comment by raviteja1992y** [comment] 2017-07-18 18:06
@rautamiekka Hi, Did 'mvn test' run fine for you? If so, can you share your log file.
For me, few test cases are failing. Some are because of SSL handshake failure(need to configure my eclipse). Remaining I have to check.

**Comment by rautamiekka** [comment] 2017-07-18 18:34
^ I haven't tried. Last time I tried to setup Eclipse or IDEA was for CraftBukkit, and it never succeed.

It's probable your ancient Java is the problem cuz there has been development in the certs and otherwise web hosting (algos getting dropped, etc.), and one of the latest 8 Updates banned the use of MD5+RSA for signing the JARs, among other things changing.

**Now** when I checked: Update 141 is the newest, when 131 was the newest not many days ago. http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Release notes overview page: http://www.oracle.com/technetwork/java/javase/8u-relnotes-2225394.html

**Comment by metaprime** [comment] 2017-07-26 04:00
`mvn test` is broken, yes. FWIW your log looks incomplete. I remember something like 10 tests failing and some number of tests with an error of some sort. The nature of this project is that websites change and through no fault of the developers, rippers (and therefore the tests which test them) become broken. There are not enough volunteer hours on this project to keep all rippers and tests working at all times, so as a policy, we do our best to fix the things that are the biggest problems for our users (starting with the biggest websites), and anyone who is not a primary maintainer fixes whatever they feel like fixing (sites they personally care about).

One option is to disable broken tests until they are fixed. But that's also a progressive time investment that would make more sense if we had more dev-hours per week.

To your other point: `mvn test` should have more tests, not less. For beginners, running `mvn test` is the absolute simplest burden I can imagine. It's quite easy compared to many projects. I'm not sure I understand how fewer tests would make things easier for beginners.

Also, more (working) tests allows beginners to know whether something they have changed has broken the tests. I understand the tests need to be working in the first place for this to be helpful.

If you're willing to indulge the broken state of the tests, you should run the tests on master, then make your changes, and run the tests again. If the number of failures has not increased ("no regressions"), then your change is probably fine.

**Comment by raviteja1992y** [comment] 2017-07-30 17:12
@metaprime In the README.md, it was written to run 'mvn test'. May be we should mention that not all tests are passing. Otherwise developers may think there is something wrong with their setup

**Comment by metaprime** [comment] 2017-08-10 09:40
@raviteja1992y Good point. Also, I should just go through and disable failing tests. No sense in running known broken tests. Doesn't let us see when things get worse / regress / a PR is bad. Unfortunately I haven't set up a travis instance for RipMeApp/ripme yet either. There's lots to do :P

**Comment by metaprime** [comment] 2017-08-10 10:17
@raviteja1992y Added note to the README

**Comment by cyian-1756** [comment] 2017-11-12 13:12
Update on this, at this point only 7 of test cases are still failing

**Comment by metaprime** [comment] 2017-11-13 09:50
I'm going to disable the remaining failing tests and open bugs for them so that we can get the CI green.

**Comment by metaprime** [comment] 2017-11-13 10:15
When #188 is merged, this issue will be closed. The test failures will be addressed in the follow-up bugs I opened.

**Closed** 2017-11-13 10:18 UTC
