### ISSUE TITLE
Instagram profile not downloading completely. Also gets stuck when multiple items in queue

### ISSUE THREAD

**Issue by ivenkrish** [RipMeApp/ripme#430] opened 2018-02-15 09:19 UTC
* Ripme version:
* Java version: Java 8 Update 131
* Operating system: MacOS
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/alexonthemic/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Album proceeds to download normally and completely

## Actual Behavior

The above profile has over 5000+ items. Only 3000+ get downloaded. The last 2 lines of the logs say:

Downloading next page
Rip complete, saved to /Users/Krish/Downloads/rips/instagram_alexonthemic

Also I see similar behavior when there are multiple Instagram links in queue. It gets stuck on "Downloading next page". I sometimes have to stop the rip and restart it again for it to proceed with the next link in the queue.

**Comment by cyian-1756** [comment] 2018-03-05 17:33
I can confirm that not all images are downloaded, but can't reproduce the ripper getting stuck

**Comment by ivenkrish** [comment] 2018-03-07 06:48
[https://i.imgur.com/vtkJBiR.png](url)

As shown in the image, there are 11 items pending in the queue, but the ripper has been stuck like this for a long time. I believe the current item has completed downloading but the "Rip complete" part and moving on to the next item doesn't happen.

**Comment by cyian-1756** [comment] 2018-03-07 17:52
> https://i.imgur.com/vtkJBiR.png

That also might be caused by the requests not timing out if there is a network isssue

**Comment by ivenkrish** [comment] 2018-03-07 19:20
Yes that's still a bug right..? I was browsing normally when RipMe was running on the background. Didn't see any network issue. If it's not a bug, what can be done to prevent this?

**Comment by cyian-1756** [comment] 2018-03-07 21:08
> Yes that's still a bug right..?

Maybe? It could be ripme or it could be instagram

> If it's not a bug, what can be done to prevent this?

I've no idea. I'll look into whats causing it

**Comment by pinnie** [comment] 2018-03-15 02:09
Experiencing a similar issue with it getting stuck on Instagram, but in my case it's only just started since updating to 1.7.25, and it's getting stuck very early on. 1.7.24 was working well (up until the JSON issue a couple of days ago).

Windows 7 64-bit, Java 8 update 161, test URL https://www.instagram.com/ithurman/

This is what happens with a clean profile (i.e. config folder deleted before starting the program):

![defaultsettings-ithurman](https://user-images.githubusercontent.com/11627353/37440254-fd56c50c-284f-11e8-8896-d5f0a5741ebd.png)

This is what happens if I change max threads to 1 (my usual setting):

![mysettings-ithurman](https://user-images.githubusercontent.com/11627353/37440383-912d1baa-2850-11e8-9efe-6defe576a330.png)

Seeing the same behaviour with any Instagram profile. Switched to a different IP in case I was getting rate limited or something by Instagram, but no change, and additional images load fine in a browser.

**Comment by cyian-1756** [comment] 2018-03-15 03:40
@pinnie 

Yea the IG ripper is currently FUBAR, I'll get on fixing it

**Comment by pinnie** [comment] 2018-03-16 05:12
1.7.26 seems to be working well for me. Sorry for hijacking the thread - thought my issue was much the same and didn't want to post a dupe.

**Comment by cyian-1756** [comment] 2018-04-19 17:28
This should be fixed in 1.7.36

**Closed by cyian-1756** 2018-04-19 17:28 UTC
Labels: confirmed
