### ISSUE TITLE
Instagram stories

### ISSUE THREAD

**Issue by sxnfxsed** [RipMeApp/ripme#205] opened 2017-11-16 19:25 UTC
Instagram added stories to their desktop site. Not sure if the same location was there before but they're viewable at https://instagram.com/stories/[username]. Would it be possible to add the ability to download stories. RipMe currently accepts the links but it rips [this profile](https://www.instagram.com/stories/)

**Comment by cyian-1756** [comment] 2017-11-16 19:41
Hitting https://instagram.com/stories/mary sends me to the login page, so I doubt this is possible without adding support for IGs private api

**Comment by sxnfxsed** [comment] 2017-11-16 20:13
Ah thats a bummer. Maybe when or if the private api is supported, the stories could be implemented. Thanks for having a look

**Comment by ohhdemgirls** [comment] 2017-11-19 00:45
Going anywhere near the API with RipMe is a bad idea, IG devs are aware of this project and actively try to stay one step ahead hence all the changes to the code lately breaking  RipMe. That's my fault, so sorry for that.

**Comment by cyian-1756** [comment] 2017-11-19 12:56
> IG devs are aware of this project and actively try to stay one step ahead hence all the changes to the code lately breaking RipMe

The only change they made that really messed up ripme was them removing the /media endpoint. And even then all I have to do was extract the json data from the pages javascript. 

Pretty much all the other bugs with the IG ripper were caused by me rewrittening the IG ripper to use ripme's abstractHTML funcs instead of the abstractJSON funcs  

> That's my fault, so sorry for that.

Are you one of those guys archiving IG?

**Comment by metaprime** [comment] 2017-11-20 02:58
I think we might still be able to do something by scraping HTML with login cookies support.

**Comment by Isaaku** [comment] 2019-10-23 22:11
This is already implemented. @cyian-1756 please close this

**Closed** 2019-10-23 22:49 UTC
Labels: cookies, enhancement
