### ISSUE TITLE
Can't download VSCO profile

### ISSUE THREAD

**Issue by ablfa** [RipMeApp/ripme#685] opened 2018-06-10 23:22 UTC
* Ripme version: v1.7.51
* Java version: N/A
* Operating system: Windows 10

## Expected Behavior

Downloading a VSCO profile.

## Actual Behavior

I tried to download a VSCO profile but it kept saying "Expected a URL to a single image or to a member profile, got [insert link]

**Comment by cyian-1756** [comment] 2018-06-11 09:52
What link are you trying to rip?

**Comment by cyian-1756** [comment] 2018-06-15 19:07
That is because of the - in the username. This should be fixed in ripme 1.7.52. I'm closing this issue as a dupe of #679

**Closed by cyian-1756** 2018-06-15 19:07 UTC
