### ISSUE TITLE
chan.sankakucomplex is only downloading preview images

### ISSUE THREAD

**Issue by TheGho7t** [RipMeApp/ripme#84] opened 2017-09-23 07:27 UTC
Is there an actual workaround for this?

I'm not the most skilled whatsoever at this sort of thing but I was going to try and edit the class file I found in the RipMe.jar. I also didn't know if I should or shouldn't as I don't know if it's even possible for this case.

It's downloading the images PROPERLY, I have actually ZERO complaints for this tool as it works brilliantly and had only messed up the first time I ever used it and never again. The problem is that it's downloading the preview image, which is a very very small watered down version of the actual image.

I also want to say that I've noticed chan.sankakucomplex has it stored on /data sometimes and then /sample other times, so I don't know if that could confuse it even more or not there.

Is there a way I can get it to open up the URL it finds to then open up the photo and then download it? Again, not the best with this stuff but that sounds almost too complicated and impossible.

Thanks.

**Comment by cyian-1756** [comment] 2017-09-23 17:44
What link where you trying to rip? What version of ripme are you using?

**Comment by TheGho7t** [comment] 2017-09-24 03:41
I tried the normal plain bland nothing special link:

[https://chan.sankakucomplex.com/](https://chan.sankakucomplex.com/)

As well as these two:

[https://chan.sankakucomplex.com/?tags=hatsune_miku+rating%3As](https://chan.sankakucomplex.com/?tags=hatsune_miku+rating%3As)

[https://chan.sankakucomplex.com/?tags=tomose_shunsaku+rating%3As](https://chan.sankakucomplex.com/?tags=tomose_shunsaku+rating%3As)

I have the latest version (1.5.7) and you can see [here](https://i.imgur.com/XvFfkv8.jpg), as well as you can see how large the files are that it is grabbing [here.](https://i.imgur.com/n7wKqOA.jpg) (As it shows in the first photo with the /preview/)

**Comment by TheGho7t** [comment] 2017-09-28 21:21
If there's really nothing I can do I can always just use a different site. I haven't tried the other sites I sometimes go to as I don't frequently go to them and honestly like the quantity more than anything on chan.sankaku (even though I can't stand the site as a whole LOL)

**Comment by rautamiekka** [comment] 2017-09-28 21:59
I confirm https://chan.sankakucomplex.com/?tags=hatsune_miku+rating%3As and https://chan.sankakucomplex.com/?tags=tomose_shunsaku+rating%3As download small previews instead.

https://chan.sankakucomplex.com/ comes up as a syntax error, demanding links similar to the ones above.

Window$ 7 Ultimate SP1 x64
Oracle Java SE 8 Update 144 x64
RipMe 1.5.7

**Comment by TheGho7t** [comment] 2017-10-03 07:08
Anything?

**Comment by cyian-1756** [comment] 2017-10-03 10:06
@TheGho7t 

It looks like a pretty simple bug that can be easily fixed, I'll get on some time in the next week or so

**Comment by TheGho7t** [comment] 2017-10-03 17:45
Okay thanks! No worries just was wondering.

**Comment by cyian-1756** [comment] 2017-10-13 04:15
@TheGho7t I've almost got everything working with the ripper, It should done and an update out in about a day or two

**Comment by TheGho7t** [comment] 2017-10-13 19:37
Thank you very much and looking forward to it!

**Comment by cyian-1756** [comment] 2017-10-16 21:28
@TheGho7t The fix is out but due to changes to the site it can only rip the first 25 pages of any tag and has to wait 8 seconds between image downloads

**Comment by TriGGer20** [comment] 2017-11-05 23:17
It still only downloads the preview images (v.1.6.5). Is there anything you can do?

**Comment by cyian-1756** [comment] 2017-11-06 00:54
@Meyham2B What url are you trying to rip?

**Comment by stacph** [comment] 2017-11-06 11:21
@cyian-1756 https://chan.sankakucomplex.com/?tags=sometag&commit=Search

**Comment by Meyham2B** [comment] 2017-11-06 11:25
@cyian-1756 Yep. We tried different tags but it’s the same.

**Comment by cyian-1756** [comment] 2017-11-06 18:44
That's odd. If I try to rip https://chan.sankakucomplex.com/?tags=t&commit=Search using 1.6.5 I'm getting fulled sized images. Can you give me a example of a url you tried to rip but that downloaded preview images?

**Comment by Meyham2B** [comment] 2017-11-06 21:30
For example https://chan.sankakucomplex.com/?tags=high_resolution&commit=Search is downloading the preview images. The file names all start with "sample", like when you manually download the preview images (ex.: sample-00caf63faf6370314794c71d3ea25c83). The full sized image, when you click on the image is 00caf63faf6370314794c71d3ea25c83 (without sample). 

I'm not sure if you already know but that's the only thing it can be:

Many preview images already are high res images but when clicking on them you get the source image, right? So with preview images **I'm not referring to the gallery view** where you can see all the posts you searched for but instead when you clicked on one and then you can click again and it shows an even higher resolution (https://chan.sankakucomplex.com/post/show/6347129 - test here by clicking on the image)

**Comment by cyian-1756** [comment] 2017-11-07 00:25
@Meyham2B Using the url https://chan.sankakucomplex.com/?tags=high_resolution&commit=Search I can reproduce this issue. I'll get on fixing it in the next few days

**Comment by Meyham2B** [comment] 2017-11-07 11:34
@cyian-1756 Awesome!

**Comment by cyian-1756** [comment] 2017-12-09 17:23
@Meyham2B This is fixed in #328 and should be in the next update

**Closed** 2017-12-11 02:59 UTC
Labels: bug
