### ISSUE TITLE
Twitter ripper not ripping past a point

### ISSUE THREAD

**Issue by puffinkins** [RipMeApp/ripme#1260] opened 2019-03-30 01:09 UTC
* Ripme version: v1.7.81
* Java version: 1.8.0_144
* Operating system: Windows 6.3.9600
* Exact URL you were trying to rip when the problem occurred: https://twitter.com/navy_126
* Please include any additional information about how to reproduce the problem: I have the config set to not downloading retweets, not sure if that plays a part.

## Expected Behavior

It should be downloading every Twitter image until the end.

## Actual Behavior

It downloads up until a certain point, then stops.

> Downloaded .\rips\twitter_account_navy_126\036_Dyy2Z91UcAAHvPK.jpg
> Downloaded .\rips\twitter_account_navy_126\041_DyZUccpUwAAFT2j.jpg
> Rip complete, saved to C:\Users\Administrator\Desktop\rips\rips\twitter_account_navy_126

The last one is "041_DyZUccpUwAAFT2j" in the log and the rip folder.
However, that is only from Feb 2, https://twitter.com/navy_126/status/1091652814915301381

There is content from as far back as March 15 that is not being ripped,https://twitter.com/navy_126/status/974229459384483841

It does not seem to be skipping any tweets, it just stops at that point.

**Comment by cyian-1756** [comment] 2019-04-04 06:04
This is a dupe of #976

**Closed by cyian-1756** 2019-04-04 06:04 UTC
Labels: duplicate
