### ISSUE TITLE
Ripme URL for 8muses is incorrect

### ISSUE THREAD

**Issue by squabbi** [RipMeApp/ripme#62] opened 2017-08-27 03:20 UTC
* Ripme version:
* Java version: 1.8.0_141
* Operating system: Microsoft Windows [Version 10.0.15063]
* Exact URL you were trying to rip when the problem occurred: https://www.8muses.com/comix/album/ebluberry-comics/the-teleporting-tavern
* Please include any additional information about how to reproduce the problem:
N/A

## Actual Behavior

Tries to rip URLs using this URL: https://cdn.ampproject.org/i/s/www.8muses.com/data/ufu/small/c85caANovBvr3UgRAqgT2zzp4djcgBJgudsWdTY+NjPKb02Z64ZTsyZqRC7WqbRrOURwAfNmNE79rvXd-+2aax6cobhJZn4vVH8GopOPWVUL92qo.jpg

where actual URL from the site should be: https://cdn.ampproject.org/i/s/www.8muses.com/data/fu/small/c85caANovBvr3UgRAqgT2zzp4djcgBJgudsWdTY+NjPKb02Z64ZTsyZqRC7WqbRrOURwAfNmNE79rvXd-+2aax6cobhJZn4vVH8GopOPWVUL92qo.jpg

Just a small change from: /data/ufu/*, to /data/fu/*

**Comment by cyian-1756** [comment] 2017-08-27 07:55
> Just a small change from: /data/ufu/, to /data/fu/

I'm pretty sure that some comics still point to /data/ufu/, at least that's how it was when I fixed the 8muses ripper [here](https://github.com/RipMeApp/ripme/pull/5). The PRs been open for a while but I assume it will be merged in sometime soon

Also in the future please search the site name before making new issues as this is a dupe of #3

**Comment by squabbi** [comment] 2017-08-27 10:27
@cyian-1756 ah right, that would make sense as other comics have downloaded properly.

And sorry about not searching properly beforehand, I was sure the search came back up with no results, but that was probably the old repo.

_Sent from my Samsung SM-G955F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cyian-1756** [comment] 2017-10-07 08:04
This was fixed in the last update (Tag 1.5.8)

**Closed by cyian-1756** 2017-10-07 08:04 UTC
