### ISSUE TITLE
cannot download whole photo album from xhamster

### ISSUE THREAD

**Issue by chokiechok** [RipMeApp/ripme#1443] opened 2019-10-04 07:24 UTC
* Ripme version:
* Java version: 64-bit Java for Windows Version 8 Update 22->
* Operating system: <winver 8.1 pro>

* Exact URL you were trying to rip when the problem occurred:
https://xhamster2.com/users/crazy-viky12/photos

* Please include any additional information about how to reproduce the problem:
When i try to copy the url Ripme cannot rip the whole album. It just stated rip complete but no downloaded contents

## Expected Behavior

Detail the expected behavior here.

## Actual Behavior
![1](https://user-images.githubusercontent.com/43874769/66188636-5f60dd80-e6ba-11e9-8c0f-dca3b97b2d61.png)

Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by rephormat** [comment] 2019-10-21 14:31
Duplicate of #1410 
@cyian-1756 recommend closing

**Closed** 2019-10-21 20:40 UTC
