### ISSUE TITLE
Unauthorized 

### ISSUE THREAD

**Issue by oheckmann** [RipMeApp/ripme#1097] opened 2018-12-09 22:30 UTC
Ripme version: 1.7.72
Java version: Version 8 update, version 191, build (build 1.8.0_191-b12)
Operating system: Windows 10
Exact URL you were trying to rip when the problem occurred: http://wytchwolf.tumblr.com
Please include any additional information about how to reproduce the problem: I rip that exact link, and without it even downloading anything, it just says 401 unauthorized, and it tries with the default api which does not work.

Actual Behavior
Its telling me the rate limit is exceeded and displaying an api key that isn't my own,
Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.
![trouble](https://user-images.githubusercontent.com/38300728/49703818-eeef4a00-fbd7-11e8-9a57-3104be11002e.PNG)

**
Afterwards, it tries to edit rip.properties to the default api.

**Comment by cyian-1756** [comment] 2018-12-11 15:49
This is a dupe of #1086 

To update your api key 

close ripme

Open the config file

%LOCALAPPDATA%\ripme on Windows

$HOME/.config/ripme on *Nix

$HOME/Library/Application Support/ripme on MacOS

Change the key at tumblr.auth to your api key

start ripme

**Closed by cyian-1756** 2018-12-11 15:49 UTC
