### ISSUE TITLE
Instagram ripper not working

### ISSUE THREAD

**Issue by yurelle** [RipMeApp/ripme#939] opened 2018-09-13 15:35 UTC
* Ripme version: 1.7.64
* Java version: 9.0.1
* Operating system: Microsoft Windows [Version 10.0.16299.547]
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/JennaMarbles/
* Please include any additional information about how to reproduce the problem:

I had an old version (v1.7.63) and I tried to download the instagram album, and it was going super slow, and not downloading things. So, I updated to the latest (v1.7.64), renamed the download folder to ("..._failedAttempt"), and initiated the download again with the new version. The new version is skipping a bunch of files, and logging them as "already downloaded" but those files were not downloaded by the last version's attempt. It continues for a short while, then the ripper stops with an output of "null" in the log. Is there a DB somewhere that ripme keeps track of DL URL's, that I need to wipe? or is this a bug in something else?

thank you,
-Yurelle

**Comment by cyian-1756** [comment] 2018-09-13 17:32
> The new version is skipping a bunch of files, and logging them as "already downloaded"

Do you have "remeber url history" checked? 

> It continues for a short while, then the ripper stops with an output of "null" in the log.

I can't reproduce this

**Comment by yurelle** [comment] 2018-09-14 00:29
Ok, I did the following

* unchecked "remember url history" and cleared the history tab
(the "clear" button on the history tab appears to be buggy. I clicked it and the all the entries stayed in the table, but I couldn't click on any of them, and when I reopened the app, they were gone. I'm guessing you're missing a repaint(), call.)
* closed the app
* deleted the partial download folder
* reopened the app
* restarted the download.

It seems to be downloading all the files now, but it's extremely slow. Is the download intentionally slowed down to prevent getting blocked by the server? I have a 16-core cpu, 64 GB of RAM, an NVME ssd, and a gigabit internet connection, so i'm fairly certain the problem is not me.

I did notice that, while downloading, the cpu usage for the ripMe process is equivalent to 1 core at 100%. If you're data transfer buffer is too small that could very well explain the cpu usage & slow download.

-Yurelle

**Comment by yurelle** [comment] 2018-09-14 01:04
Ok, nevermind. Apparently the slow downloading was "my" fault. It was a super stupid Windows 10 configuration option that brought my system to its knees. I would not have thought that possible, but apparently it is. I fixed that config option, and your app is flying through the downloads.

It looks like my URL History db got corrupted somehow, and that was causing problems; but the slow download was on me. I apologize for blaming your code, when I should have blamed windows 10. :-)

-Yurelle

**Comment by cyian-1756** [comment] 2018-09-14 11:49
If everything is working now I'm going to close this

**Closed by cyian-1756** 2018-09-14 11:49 UTC
Labels: can't repro
