### ISSUE TITLE
[REQUEST] rip tumblr archives

### ISSUE THREAD

**Issue by droidberg** [RipMeApp/ripme#551] opened 2018-04-30 01:04 UTC
any chance of adding the ability to rip tumblr archives?? to be more specific, rip by post types such as only videos or images? i often rip tumblr pages just for videos that are huge and end up deleting most of content because its stuff i dont want like images.

**Comment by cyian-1756** [comment] 2018-06-06 06:39
I'm closing this as a dupe of #198

**Closed by cyian-1756** 2018-06-06 06:39 UTC
Labels: duplicate, enhancement
