### ISSUE TITLE
(NSFW) anon-ib.com invalid 

### ISSUE THREAD

**Issue by onigumo1990** [RipMeApp/ripme#329] opened 2017-12-09 17:53 UTC
New url is http://usa.anon-ib.su

* Ripme version: 1.7.7
* Java version: 
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

* Operating system: 
Distributor ID: Ubuntu
Description: Ubuntu 16.04.3 LTS
Release: 16.04
Codename: xenial

* Exact URL you were trying to rip when the problem occurred:
None of the URLs work, but here's one for an example: http://usa.anon-ib.su/al/

* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Expected the ripper to rip the images

## Actual Behavior

Error:
```
[!] Error while ripping URL http://usa.anon-ib.su/al/
java.lang.Exception: No compatible ripper found
        at com.rarchives.ripme.ripper.AbstractRipper.getRipper(AbstractRipper.java:372)
        at com.rarchives.ripme.App.rip(App.java:68)
        at com.rarchives.ripme.App.ripURL(App.java:180)
        at com.rarchives.ripme.App.handleArguments(App.java:172)
        at com.rarchives.ripme.App.main(App.java:59)
```

**Comment by rephormat** [comment] 2018-02-13 00:39
Can not recreate with latest version.  @onigumo1990 Can we close this?

**Comment by onigumo1990** [comment] 2018-02-13 00:52
I still get the issue with the latest version:

```
Loaded log4j.properties
Initialized ripme v1.7.19
[!] Error while ripping URL http://usa.anon-ib.su/al/
java.lang.Exception: No compatible ripper found
        at com.rarchives.ripme.ripper.AbstractRipper.getRipper(AbstractRipper.java:424)
        at com.rarchives.ripme.App.rip(App.java:72)
        at com.rarchives.ripme.App.ripURL(App.java:192)
        at com.rarchives.ripme.App.handleArguments(App.java:180)
        at com.rarchives.ripme.App.main(App.java:59)
```

**Comment by cyian-1756** [comment] 2018-02-13 10:56
I can also comfirm this with ripme 1.7.19

**Comment by rephormat** [comment] 2018-02-13 13:39
@cyian-1756 I guess I'm trying to determine whether this is a bug or not.  I can't recall anytime I was able to rip an entire board as the author is attempting to do.  I had to specify the thread I wanted ripped.  Thus this would be an enhancement request and not a bug report.

**Comment by onigumo1990** [comment] 2018-02-13 14:02
If that's the case, that it never worked, then it is indeed an enhancement request.

**Closed** 2018-06-13 12:21 UTC
Labels: confirmed
