### ISSUE TITLE
instagram issue

### ISSUE THREAD

**Issue by wooki0** [RipMeApp/ripme#608] opened 2018-05-21 20:36 UTC
* Ripme version: 1.7.47
* Java version: 8 update 171
* Operating system: windows 10
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/heatherbone_/
* Please include any additional information about how to reproduce the problem:

rip an instagram album
## Expected Behavior
Rip album till complete
Detail the expected behavior here.
add url rip till done
## Actual Behavior
add url not completing rip  will dl a few images then get Null as an error
Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

**Comment by rautamiekka** [comment] 2018-05-21 21:59
Edit the OP with RipMe and Java versions ...

**Comment by cyian-1756** [comment] 2018-05-21 23:45
I can't reproduce this

**Comment by cyian-1756** [comment] 2018-05-22 19:03
@wooki0 

I'm closing this as invalid. I'll reopen it when you fill out the issue template

**Comment by wooki0** [comment] 2018-05-22 20:42
so far so good no real problems today it was acting up yesterday. it would only pull a few pics then error with null yesterday seems ok today though

**Comment by Ectomind1990** [comment] 2018-05-23 16:40
Had this also. Was intermittent. Tried the same account the next day without problems. From memory the title of the window just said "null", the log tab of the window just said "null"

But I look in the log.txt file for that account and see
```
2018-05-21 20:49:51,511 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.lang.NullPointerException
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.pageHasImages(InstagramRipper.java:395)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getNextPage(InstagramRipper.java:377)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:85)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:533)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by m-r-k** [comment] 2018-05-25 05:29
Same here.
Java: openjdk version "1.8.0_171"
Ripme: 1.7.47

**Comment by cyian-1756** [comment] 2018-06-01 20:15
Is anyone still running into this?

**Comment by Ectomind1990** [comment] 2018-06-02 20:06
Sometimes, this is from log.txt of an account where it happened today. It only saved 12 files when there are >100 posts on the account.

```
2018-06-02 18:08:11,979 DEBUG ripper.DownloadFileThread .run() Request properties: {Cookie=[], User-agent=[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36], accept=[*/*]}
2018-06-02 18:08:12,351 DEBUG ripper.DownloadFileThread .run() Status code: 200
2018-06-02 18:08:13,030 INFO  ripper.AbstractRipper .getPage() Unable to get query_hash
2018-06-02 18:08:13,034 INFO  ripper.AbstractRipper .getPage() Connection reset
2018-06-02 18:08:13,035 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.lang.NullPointerException
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.pageHasImages(InstagramRipper.java:395)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getNextPage(InstagramRipper.java:377)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:92)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:555)
	at java.lang.Thread.run(Thread.java:748)
2018-06-02 18:08:13,038 DEBUG ripper.AbstractRipper .waitForThreads() Waiting for threads to finish

**Comment by Ectomind1990** [comment] 2018-06-02 20:08
I would love to have a setting "wait at least this long before loading the next page". I am not in a hurry so I would set this to like N=30 seconds.  Would be great after getNextPage fails for any reason if it retries after 2N seconds (60 for me) and again after 4N and 8N and 16N...

**Comment by cyian-1756** [comment] 2018-06-02 20:21
@Ectomind1990 

> Version 1.7.49 though

Heads up Version 1.7.49 updater is bugged meaning it'll never realize that a new version of ripme is available. You'll have to manually update to 1.7.50

**Comment by Ectomind1990** [comment] 2018-06-02 21:32
> You'll have to manually update to 1.7.50

thanks, done it

**Comment by Ectomind1990** [comment] 2018-06-06 23:10
Happening every time for me right now
1.7.50 but it was working great yesterday

```
2018-06-06 23:01:44,393 ERROR ripper.AbstractRipper .run() Got exception while running ripper:
java.lang.NullPointerException
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.pageHasImages(InstagramRipper.java:395)
	at com.rarchives.ripme.ripper.rippers.InstagramRipper.getNextPage(InstagramRipper.java:377)
	at com.rarchives.ripme.ripper.AbstractJSONRipper.rip(AbstractJSONRipper.java:92)
	at com.rarchives.ripme.ripper.AbstractRipper.run(AbstractRipper.java:555)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Hrxn** [comment] 2018-06-07 04:47
Probably some site change, again..

**Closed** 2018-06-07 10:56 UTC
Labels: can't repro
